### ISSUE TITLE
docs: package-name needs to be quoted if scoped

### ISSUE THREAD

**Issue by coreyfarrell** [google-github-actions/release-please-action#10]
The README.md example release-please.yml sets `package-name: release-please-action`.  This is good for unscoped packages but for `package-name: "@myorg/package"` it is mandatory to quote the scoped package name.  This tripped me up the first time I attempted to use this package.  Partly because I'm not super familiar with yaml parse rules so creating yaml files is often copy-pasta for me.

I'm not sure if you want to just quote the `release-please-action` in your example or add a comment?  I can post a PR if you let me know how you want this handled.

**Comment by bcoe** [comment]
@coreyfarrell perhaps we could add a note that both mentions that `package-name` is optional for some types of releasers, e.g., node which reads it from `package.json`, and that you my want to use a quoted string if you have special characters.
