### ISSUE TITLE
feature request: support rust

### ISSUE THREAD

**Issue by gengjiawen** [google-github-actions/release-please-action#163]
Will rust support can be on the roadmap ? Thanks for this project.

**Comment by bcoe** [comment]
@gengjiawen I don't know much about rust, but would certainly be open to adding support with help.

**Comment by gengjiawen** [comment]
I am now using simple to do this, https://github.com/gengjiawen/monkey-rust/pull/16.
Is there any hook I can use to change version in this PR, like https://github.com/gengjiawen/monkey-rust/blob/aad6a58b7203c3069dd45ee0d4a92ca047cb276f/wasm/Cargo.toml#L3

**Comment by bcoe** [comment]
Initial Rust support has been added by @fasterthanlime, please let me know if you bump into any issues.

@fasterthanlime thank you 🎉

**Comment by gengjiawen** [comment]
I am seeing documentation update. I just need to change type to rust ?

**Comment by fasterthanlime** [comment]
> I am seeing documentation update. I just need to change type to rust ?

Yes, you need to change the type to `rust`.

Additionally, you may want to add the current version of your workspace dependencies, so for example this line:

https://github.com/gengjiawen/monkey-rust/blob/65587f783911c2bd81bf37152b187805f403449f/interpreter/Cargo.toml#L23

Should probably read:

```toml
monkey-parser = { version = "0.4.1", path = "../parser" }
```

Whenever `monkey-parser` is updated, then the version of monkey-parser in `interpreter`'s dependencies will also be bumped.

---

You may run into a problem: it looks like you're releasing all crates with the same version number (0.4.1 everywhere), whereas the current Rust support assumes you're releasing crates independently.

Adding support for "all crates of the workspace are bumped together" could be done in the future, but it's not supported yet.

**Comment by gengjiawen** [comment]
![image](https://user-images.githubusercontent.com/3759816/103994849-8cac0d80-51d2-11eb-91ee-ecb45f72f41d.png)

I previously use this. But I found it pretty redundant given it's local dependency.

**Comment by fasterthanlime** [comment]
> I found it pretty redundant given it's local dependency.

`path` dependencies work great when developing a cargo workspace, but when publishing to crates.io, you need to specify a version as well, otherwise how would it know what to install?

I'm assuming `cargo-workspaces` edits your `Cargo.toml` before publishing.

**Comment by gengjiawen** [comment]
Thanks for the clarification.
