### ISSUE TITLE
Action throw error without package-name

### ISSUE THREAD

**Issue by rudywaltz** [google-github-actions/release-please-action#164]
If not set package-name the github action throw an error 

`Error: release-please failed: The "path" argument must be of type string. Received type number`
it's worked one week before and the release version was just `v1.2.4` now only working if I add some name (I don't wanna publish my code as an npm package, so I just would like to use simply the version name if it is possible)

this is the broken action https://github.com/rudywaltz/workflow-test/runs/1539955006?check_suite_focus=true

and this is with package name https://github.com/rudywaltz/workflow-test/runs/1539927347?check_suite_focus=true

Thank you
rudywaltz

it's worked 2 days ago if I'm correct
<img width="714" alt="Screenshot 2020-12-11 at 22 55 31" src="https://user-images.githubusercontent.com/395555/101958670-12549180-3c04-11eb-9cd7-b6835faec8dd.png">

**Comment by rudywaltz** [comment]
I had time to test a little bit, the bug was introduced the latest version (2.12.2)
https://github.com/rudywaltz/workflow-test/runs/1550339587?check_suite_focus=true
the previous working (2.12.1)
https://github.com/rudywaltz/workflow-test/runs/1550323306?check_suite_focus=true

**Comment by bharathkkb** [comment]
Looks like this is also broken for me 
https://github.com/google-github-actions/upload-cloud-storage/runs/1554143801

**Comment by rudywaltz** [comment]
sorry for the accidental closing (it was because of a commit message in my repo)

**Comment by bcoe** [comment]
@bharathkkb @rudywaltz for clarification, when you set `package-name` does it work as expected?

**Comment by bcoe** [comment]
I can confirm this is fixed, sorry for the trouble 👍

**Comment by rudywaltz** [comment]
Hi @bcoe , yes with package-name it worked.
Thank you for the fix, I will try soon, but I don't expect any issue
