### ISSUE TITLE
[BUG] npm publish process skipped

### ISSUE THREAD

**Issue by gengjiawen** [google-github-actions/release-please-action#172]
Related job: https://github.com/gengjiawen/monkey-rust/runs/1636641958.

Is it because publish is limited to Node type ?

**Comment by bcoe** [comment]
@gengjiawen giving your action a quick ready, there's this step:

`        if: ${{ steps.release.outputs.release_created }}`

Which decides whether or not to publish, but you haven't named any of your steps `release`.

I think if you add the `id: release` to the step represented by `uses: GoogleCloudPlatform/release-please-action@v2` it should start working for you (see: [yargs](https://github.com/yargs/yargs/blob/master/.github/workflows/release-please.yml#L9).

**Comment by gengjiawen** [comment]
Thanks. Now I get E404 in https://github.com/gengjiawen/monkey-rust/runs/1647197523.

I have set the token in my repo. Any other thing can cause this ?

**Comment by gengjiawen** [comment]
Or this because this is my first publish on npm, current action only supports update ?
