### ISSUE TITLE
The Boolean function make input string always set to true

### ISSUE THREAD

**Issue by yi-Xu-0100** [google-github-actions/release-please-action#215]
I found the action to use the `Boolean` function to parse input. See in:

https://github.com/google-github-actions/release-please-action/blob/484099d9695e3107b5d0bab3f953ab900f69f9d8/index.js#L7-L9

but the `core.getInput` function return string. It will cause the `bump-minor-pre-major` always to be true.

https://github.com/actions/toolkit/blob/228a9534d1f2e5a31363a5ffa9ab47629c22d337/packages/core/src/core.ts#L77-L91

maybe change this logic will fix the issue (https://github.com/googleapis/release-please/issues/558)

**Comment by pragmaticivan** [comment]
`core.getInput('bump-minor-pre-major') === 'true'` is probably more appropriate here?

**Comment by yi-Xu-0100** [comment]
@bcoe I perfer to use `core.getInput('bump-minor-pre-major').toUpperCase() === 'TRUE'`. what do you think?😄

**Comment by pragmaticivan** [comment]
It should work, although we should invalidate anything different from the intent that was `true / false` as a js boolean.

**Comment by yi-Xu-0100** [comment]
@pragmaticivan 

but the workflow file is yaml format, and In yaml format, the `y|Y|yes|Yes|YES|n|N|no|No|NO|true|True|TRUE|false|False|FALSE|on|On|ON|off|Off|OFF` should be transformed into boolean type. See in [yaml-type-bool](https://yaml.org/type/bool.html).

In [js-yaml playground](http://nodeca.github.io/js-yaml/), it only support `true|True|TRUE|false|False|FALSE`, and I think this is the minimum requirement. To simplify detection, I used `.toUpperCase()` instead of a more accurate matching method.

This is a personal opinion, and I think no matter which method is followed, it is better to give examples in README. 😁

**Comment by pragmaticivan** [comment]
I agree with you. I guess I also don't like how yaml handles that haha

**Comment by bcoe** [comment]
@pragmaticivan @yi-Xu-0100 I would like to support anything supported as boolean thorough YAML, what if we added `js-yaml` as a  dependency, and actually parse the field? with tests.

**Comment by yi-Xu-0100** [comment]
@bcoe

The `core` library processes the input value so that the return value is string. We can only process the return value instead of directly parsing the configuration file in yaml format. Is it too large to add a parsing library? Even if we want to support all yaml formats, I think it can be done by matching strings, such as the following way:

```js
function getBooleanInput(input) {
  const trueValue = ['true','True','TRUE', 'yes', 'Yes', 'YES', 'y', 'Y', 'on', 'On', 'ON']
  const falseValue = ['false','False','FALSE', 'no', 'No', 'NO', 'n', 'N', 'off', 'Off', 'OFF']
  var stringInput = core.getInput(input)
  if(trueValue.indexOf(stringInput) > -1) return true
  if(falseValue.indexOf(stringInput) > -1) return false
  core.setFailed(`release-please failed: Wrong input value of ${input}`)
}

const bumpMinorPreMajor = getBooleanInput('bump-minor-pre-major')
```

**Comment by bcoe** [comment]
@yi-Xu-0100 I'm supportive of this helper, I'd add a link to the yaml spec that describes the possible inputs for a boolean value 👍

**Comment by bcoe** [comment]
@yi-Xu-0100 do you think that #233 will address the bug also discussed [here](https://github.com/googleapis/release-please/issues/558)?

**Comment by yi-Xu-0100** [comment]
@bcoe The #233 only make the input of boolean type can set to be false. but no helpful for the https://github.com/googleapis/release-please/issues/558

As the discussed in #168 and what I suggest in https://github.com/googleapis/release-please/issues/558#issuecomment-778759019 : Maybe we can set the default version to '0.1.0' in the node type when `bump-minor-pre-major` is true. 

I will try to make a PR for the `release-please`, wait for my good news. 😁

**Comment by yi-Xu-0100** [comment]
@bcoe See in https://github.com/googleapis/release-please/pull/776 😀
