### ISSUE TITLE
Use Typescript for release-please-action

### ISSUE THREAD

**Issue by pragmaticivan** [google-github-actions/release-please-action#221]
Motivation:

It would  enforce type coming from release-please package.

Artifacts:

* https://github.com/actions/typescript-action (Possible inspiration)

**Comment by bcoe** [comment]
👍 seems like this would be a good decision. If we do so, I think we could use the standard TypeScript configuration that my team uses in libraries [like this](https://github.com/googleapis/nodejs-secret-manager):

* use a similar `tsconfig`.
* use `gts` for linting.

**Comment by pragmaticivan** [comment]
That sounds good to me.
