### ISSUE TITLE
Can this be used to create PRs from a dev branch?

### ISSUE THREAD

**Issue by ChildishGiant** [google-github-actions/release-please-action#226]
I'm trying to set this up so that it makes PRs from a dev branch onto a master branch but can't work out how to. Many thanks.

**Comment by pragmaticivan** [comment]
hi @ChildishGiant are you trying to release versions from a dev branch? or just send a PR?

If a PR is all you want, there are other actions specialized on that specific feature. Ex: https://github.com/repo-sync/pull-request

**Comment by ChildishGiant** [comment]
The hope is to have a PR from dev always open and for this to update the changelog and release so that when it's merged it'll have the correct version etc

**Comment by pragmaticivan** [comment]
You can have any branch as `target for release` by using the `default-branch` option (will be available today or tomorrow on the latest version).

This lib has 2 functionalities:
1. Create a release pull request from the source branch when a new commit happens.
* ex, if your default-branch is set to `main`, every time you merge something into main, it will trigger creating a PR for a new release.
* The PR will contain changelog and version bump depending on which lang you are using.

2. Create a GitHub release and tag once the release pull request is merged.
* ex, if your default-branch is set to `main`, every time you merge a `release pr from step 1`, it will automatically go ahead and create a GitHub release + tag that release.

Both options support default-branch (branch where this action will read new versions from).

**Comment by ChildishGiant** [comment]
Ah okay so for what I want I need to look at other tools. Thank you for the help 😄
