### ISSUE TITLE
PR not created.

### ISSUE THREAD

**Issue by gengjiawen** [google-github-actions/release-please-action#227]
https://github.com/gengjiawen/node-gyp/actions?query=workflow%3Arelease-please
![image](https://user-images.githubusercontent.com/3759816/107965729-d237d380-6fe5-11eb-9d90-fae38925becc.png)

I am migrating node-gyp to this action. But I am not understanding the requirements

**Comment by pragmaticivan** [comment]
hi @gengjiawen are you trying to test it out from your Fork?

**Comment by bcoe** [comment]
@gengjiawen quickly digging through the `node-gyp` repo, I don't see many commits that are labeled `fix:` or `feat:`, which are the commits that get picked up and initiate a release.

You can override this with the `changelog-types`, if you'd like for instance to kick off releases as a side effect of updating `docs`.

**Comment by gengjiawen** [comment]
> hi @gengjiawen are you trying to test it out from your Fork?

Yeap. I also have created a test PR in my fork, not sure it count as PRs.

**Comment by gengjiawen** [comment]
> @gengjiawen quickly digging through the `node-gyp` repo, I don't see many commits that are labeled `fix:` or `feat:`, which are the commits that get picked up and initiate a release.
> 
> You can override this with the `changelog-types`, if you'd like for instance to kick off releases as a side effect of updating `docs`.

Thanks, that's the case.
