### ISSUE TITLE
create official badge

### ISSUE THREAD

**Issue by gengjiawen** [google-github-actions/release-please-action#230]
I really like this tool. Maybe an official badge so we can add it to `README.md` to make it more known.

**Comment by bcoe** [comment]
@gengjiawen I think this is a good idea.

**Comment by gengjiawen** [comment]
@chingor13 Not stable, please reopen. And stop this mess

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/3759816/207202356-608d6682-3f8f-4a87-98f6-e82eda6ec269.png">
