### ISSUE TITLE
[Bug] bump version wrong for node project

### ISSUE THREAD

**Issue by gengjiawen** [google-github-actions/release-please-action#231]
PR: https://github.com/gengjiawen/node-gyp/pull/2/files

![image](https://user-images.githubusercontent.com/3759816/108016482-97698600-704d-11eb-999d-d349d9783840.png)

**Comment by pragmaticivan** [comment]
hi @gengjiawen your Fork has less tags available. The latest published tag was 6.0 https://github.com/gengjiawen/node-gyp/tags

To make it properly work you would need to make to push the upstream repo tags to your fork.

**Comment by bcoe** [comment]
@gengjiawen, as @pragmaticivan says, you will need to push a `v7.1.2` tag to GitHub.

You can then close the release PR, and delete the v6.x.x branch and re-run the action.

**Comment by gengjiawen** [comment]
> @gengjiawen, as @pragmaticivan says, you will need to push a `v7.1.2` tag to GitHub.
> 
> You can then close the release PR, and delete the v6.x.x branch and re-run the action.

But wouldn't use version in `package.json` first make more sense ? Especially for lots of legacy projects.

**Comment by Val-istar-Guo** [comment]
I get same issue:

The action auto bump version from 1.0.0 to 0.2.0:
https://github.com/mili-project-manager/mtpl-nuxtjs/runs/3231980315?check_suite_focus=true

I had used standard-version release the version from 0.1.0 to 1.0.0. And publish package manually.(NO Breaking Change). And then, action-semantic-release not behave as expected.

tags, the version of package.json are setted 1.0.0. why bump version to 0.2.0?
this confuse me.

Can't I manually modify the version number？

**Comment by bcoe** [comment]
@Val-istar-Guo to get your project bootstrapped, you can use:

```
build: correct version for next release

Release-As: v1.0.1
```

Once you've done a first release with relase-please, it should work as expected.

**Comment by Val-istar-Guo** [comment]
@bcoe`release-please` is not compatible with `standard-version`?  I am confused about this.
