### ISSUE TITLE
prepend changelog instead of overwrite for legacy project

### ISSUE THREAD

**Issue by gengjiawen** [google-github-actions/release-please-action#232]
Same from https://github.com/gengjiawen/node-gyp/pull/2/files.

The history changelog is very important. Maybe just prepend new in file header.

**Comment by pragmaticivan** [comment]
I doubt it will be able to append the current changelog as it's not following the same format. (You might be able to regenerate everything from the first tag though)


The logic for generating changelog is actually managed by release-please npm lib.
Ref: https://github.com/googleapis/release-please/blob/master/package.json#L65-L66

**Comment by bcoe** [comment]
we attempt to detect prior releases and keep the prior CHANGELOG entry, we just don't understand the format:

`v7.1.2 2020-10-17`

I could imagine adding support for this, for the benefit of `node-gyp`.

**Comment by bcoe** [comment]
@gengjiawen another option would be manually changing the CHANGELOG before merging the first time, at which point future releases will find the new header format correctly.
