### ISSUE TITLE
Add config option to customise release title

### ISSUE THREAD

**Issue by Fdawgs** [google-github-actions/release-please-action#260]
Hi there,

Currently this action prepends the repo (or package?) name to the semver tag to create the release title i.e. `example-repo v1.0.0`.
It would be great if this could be toggled on or off so the release titles could just be the semver tag. 😄

**Comment by bcoe** [comment]
@Fdawgs could you share the configuration you're using? Unless you set `--monorepo-tags` to true, it shouldn't include the package name in the tag, this is only done to differentiate between libraries if there are multiple libraries in one repository.

**Comment by bcoe** [comment]
I found one of your repos:

https://github.com/Fdawgs/test-gh-actions/releases/tag/v1.0.2

I follow now, the issue isn't the tag, it's the title for the release 👍

**Comment by Fdawgs** [comment]
> I found one of your repos:
> 
> 
> 
> https://github.com/Fdawgs/test-gh-actions/releases/tag/v1.0.2
> 
> 
> 
> I follow now, the issue isn't the tag, it's the title for the release 👍 

Brilliant, thanks @bcoe, that's what I meant!

**Comment by mayank99** [comment]
How much work would it be to add this? The repo/package name in the release title is redundant, so it would be nice to be able to remove it.

**Comment by bcoe** [comment]
@mayank99 I haven't thought through this problem, so I'm not sure how much work it would be.

The changes would be here: https://github.com/googleapis/release-please

**Comment by mayank99** [comment]
If it's okay, I will try to work on this and create a PR if I'm successful. Hopefully it's not too complicated 🤞

**Comment by bcoe** [comment]
@mayank99 I would take a look at [title-pattern](https://github.com/googleapis/release-please/blob/master/src/bin/release-please.ts#L94) and see if it does what you're looking for.

If so, I would happily take a patch accepting this parameter.

**Comment by Fdawgs** [comment]
Seems it now uses version name by default and doesn't include package name. So this is fixed!
