### ISSUE TITLE
Wrong version detection

### ISSUE THREAD

**Issue by PiotrRut** [google-github-actions/release-please-action#263]
I have a Python package which I tag and version with `v` prepended, like `v1.0.2`, `v1.1` and so on. I have recently integrated this action into my repository, however it seems it has gotten the versioning wrong. Current tag and version is `v1.1`, and the newly created release PR by this automation want's to bump version to `1.1.0` -> see [here](https://github.com/PiotrRut/BetterGitCLI/pull/2).

It seems like the automation thinks the last tag was `v1.0.2`, but the last one was actually `v1.1` Have I done something wrong with the config?

**Comment by yi-Xu-0100** [comment]
May be it only detect the version like `vx.y.z` and did not detect the version like `vx.y`

**Comment by PiotrRut** [comment]
Yeah hence my question if that is the case

**Comment by yi-Xu-0100** [comment]
@PiotrRut The version format should fit the [Semantic Versioning 2.0.0](https://semver.org/). 😅

Maybe you can change the tag to fit the format.

**Comment by PiotrRut** [comment]
Ahh I see, wasn't sure if it would accept it without the trailing 0 - will use a 0.0.0 tag next time, thank you 😃
