### ISSUE TITLE
Python release with pyproject.toml & poetry.

### ISSUE THREAD

**Issue by ygworldr** [google-github-actions/release-please-action#287]
I have a Python project that uses `pyproject.toml` and [poetry](https://python-poetry.org/). The authoritative version for the project is in both the `pyproject.toml` and in `<PACKAGE>/__init__.py` as `__version__`.

I know there is a python release-type but that clearly won't work for me. 

How can I modify the `.github/workflows/release-please.yml` file to change the version in those files as well?

**Comment by bcoe** [comment]
We just released a version with support for `pyproject.toml`, thank you @Mesteery 🥳
