### ISSUE TITLE
Tag release after the action has run

### ISSUE THREAD

**Issue by mraerino** [google-github-actions/release-please-action#288]
We're using this action and its output to trigger a publish workflow in the same job if a new release PR has just been merged, similar to this example: https://github.com/google-github-actions/release-please-action#automating-publication-to-npm

Now if the publishing steps fail you'll end up in an inconsistent state:
- Release-please has already tagged a release and marked the PR as processed
- The published artifact does not actually exist

This could be solved by tagging the release and marking the release PR as tagged **after the publish steps are done**.
More specifically, you can use a `post` step in github actions to do this: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#post

Would you consider this a good idea?

**Comment by erezrokah** [comment]
This is 💯 
Since tagging and releasing can also fail, another option is to have a revert operation which will revert the PR, delete the release+tag and re-create the release PR so it can be retried.

**Comment by bcoe** [comment]
@mraerino this seems like a good suggestion 👍

**Comment by jthegedus** [comment]
Has this been closed because the feature requested has been implemented, or solely because of no comments? I found this recently but only 👍 the OP instead of spamming the thread with comments. Granted GitHub doesn't visualise the history of reactions to OP, but if I need to comment on the thread to keep the feature request "active" I will happily do so.

**Comment by GordonSmith** [comment]
Just a "me too" comment - in my case I stamp the package version into the bundled JS and commit the change prior to publish, but this happens after the repo is tagged...
