### ISSUE TITLE
Document special prefixes emitted by manifest releases

### ISSUE THREAD

**Issue by bcoe** [google-github-actions/release-please-action#297]
We should document the outputs set by manifest releases, e.g., `path--tag_name`, `releases_created`.

**Comment by hugomrdias** [comment]
```text
"releases_created": "true",
"packages/one--release_created": "true",
"packages/one--major": "1",
"packages/one--minor": "2",
"packages/one--patch": "2",
"packages/one--sha": "fe5efccaf5c3d11c18f5a357e848276ec6cc1180",
"packages/one--version": "1.2.2",
"packages/one--pr": "27",
"packages/one--html_url": "https://github.com/hugomrdias/mono-release/releases/tag/one-v1.2.2",
"packages/one--name": "one one-v1.2.2",
"packages/one--tag_name": "one-v1.2.2",
"packages/one--upload_url": "https://uploads.github.com/repos/hugomrdias/mono-release/releases/48621032/assets{?name,label}",
"packages/one--draft": "false",
"packages/one--body": "\n\n### Bug Fixes\n\n* **one:** ddd ([56625f7](https://www.github.com/hugomrdias/mono-release/commit/56625f7922d6dd3a95eb703629565eeeacdcdec2))\n"
```

Theres an issue if you use a folder for your packages, github doesnt like slashs in the outputs vars and raises a Unexpected symbol error

**Comment by hugomrdias** [comment]
found a solution `if: ${{ steps.tag-release.outputs['packages/two--release_created'] }}`

**Comment by ChipWolf** [comment]
I don't see any of these special outputs from the manifest releaser @bcoe @hugomrdias, did either of you do something special for this behavior?

**Comment by bcoe** [comment]
Some of these outputs may be related to the regression @phated mentions, will look soon.

**Comment by mshrtsr** [comment]
Thank you for the @hugomrdias's solution https://github.com/google-github-actions/release-please-action/issues/297#issuecomment-907698520.
It worked for my problem.

However, I think it is better to replace special symbols like `/` with `-` or `_`.

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputsoutput_id

> The `<output_id>` must be a unique identifier within the outputs object. The `<output_id>` must start with a letter or `_` and contain only alphanumeric characters, `-,` or `_`.
