### ISSUE TITLE
bug: ignores `version.txt` version when initially created

### ISSUE THREAD

**Issue by jef** [google-github-actions/release-please-action#30]
### Description

It overwrites what is in `version.txt` when it's explicitly set when initially integrating the action. Not sure if this is intended behavior or not.

Thanks!

Example: https://github.com/jef/forest-night-jetbrains/pull/6

### Use case

It's required that this plugin starts at `1.0.2` as I didn't have any releases via git beforehand, but when I set it to `1.0.2` it overwrites it to `1.0.0`.

### Alternative solution

I suppose I can go make tags in git on previous commits, but not sure if that's the best solution (or if that works).

**Comment by bcoe** [comment]
@jef yeah, bootstrapping an old repo with release-please is a little clunky. I think the approach that currently works best is tagging the first release.

**Comment by jef** [comment]
Got it, okay. So just tag the latest master with whatever version you want to start with is the best approach?

**Comment by jef** [comment]
I'll go ahead and close this out. Doesn't make too much sense to keep it alive.

Thanks!
