### ISSUE TITLE
[Feature Request] Expose version data when release_created is false

### ISSUE THREAD

**Issue by amadkinnon** [google-github-actions/release-please-action#308]
It would be nice to know the version information to use in a workflow when a release is NOT created. For instance, building release candidate artifacts (v1.1.1-rc1) to push to QA. When the release is created, we  would simply promote those artifacts to production instead of rebuilding.

Thoughts or another workflow solution?

**Comment by live627** [comment]
I don't know if this helps you but here's how I grab the version

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: ${{ env.MOD_NAME }}
      - uses: actions/github-script@v3
        id: vars
        with:
          script: |
            const response = await github.pulls.get({
              pull_number: ${{ steps.release.outputs.pr }},
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.info("\u001B[32m✔\u001B[39mBranch: \u001B[1;32m" + response.data.head.ref);
            core.setOutput("branch", response.data.head.ref);
        if: ${{ steps.release.outputs.pr && !steps.release.outputs.release_created }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.branch }}
        if: ${{ steps.release.outputs.pr && !steps.release.outputs.release_created }}
      - if: ${{ steps.release.outputs.pr && !steps.release.outputs.release_created }}
        run: |
          version=$(cat ./version.txt)

I then use this info to add  a commit to the release branch updating version numbers in various files.

**Comment by ferrarimarco** [comment]
@chingor13 Can we please reopen this?

There are a couple of steps about pushing additional tags in our Git repository that we cannot test because version data is available only when publishing a release. At least this is my understanding: https://github.com/google-github-actions/release-please-action/blob/cc61a07e2da466bebbc19b3a7dd01d6aecb20d1e/src/index.ts#L162-L193

Thanks!
