### ISSUE TITLE
Reset version from version.txt file

### ISSUE THREAD

**Issue by ygueguin** [google-github-actions/release-please-action#328]
Hello ! 
I tried to use this action in a Java Project, creating a version.txt file from pom.xml, it feel like it dont care about the version.txt file committed, like it just compare with the previous version.txt file merged from release-please-action
I would like to know if it s possible to 'reset' the version number ? Or maybe force the release number ?
Thanks !

**Comment by live627** [comment]
[Use the `simple` release type](https://github.com/google-github-actions/release-please-action#release-types-supported). That's what I do for my PHP project.
