### ISSUE TITLE
force release

### ISSUE THREAD

**Issue by gengjiawen** [google-github-actions/release-please-action#345]
I made a mistake by forcing push. Looks like now I can't use it anymore.

Any workaround

https://github.com/gengjiawen/crawler-toolbox/runs/3400020230

```console
Run GoogleCloudPlatform/release-please-action@v2
  with:
    release-type: node
    token: ***
    fork: false
    clean: true
    bump-minor-pre-major: false
    monorepo-tags: false
    pull-request-title-pattern: chore${scope}: release${component} ${version}
✔ creating release v1.2.0
Error: release-please failed: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
```

**Comment by bcoe** [comment]
@gengjiawen I think perhaps it would work if you delete both the release and tag?

Did you figure out a workaround? sorry for the slow triaging.

**Comment by gengjiawen** [comment]
> Did you figure out a workaround?

Yeap. I have to manually fix changelog and downgrade version.
