### ISSUE TITLE
The optional release-type input (or none)

### ISSUE THREAD

**Issue by alexey-igrychev** [google-github-actions/release-please-action#349]
Thanks for the action, which greatly improve the CI in our projects.

We want to use this action not only for [supported release types](https://github.com/google-github-actions/release-please-action#release-types-supported) but also for arbitrary ones without bumping version in any project files (for instance, for projects written in Go). 

At the moment, using release type `simple` is the only available option. It seems to me that making the field optional won't cost you anything and will save users from an unnecessary version.txt file.

**Comment by bcoe** [comment]
@alexey-igrychev this seems like a reasonable feature request, could I bother you to open the issue [here](https://github.com/googleapis/release-please), this is where the functionality is actually implemented.

**Comment by alexey-igrychev** [comment]
duplicate https://github.com/googleapis/release-please/issues/1040
