### ISSUE TITLE
FR: Enable git flow patterns

### ISSUE THREAD

**Issue by codytipton-hpg** [google-github-actions/release-please-action#387]
Currently release-please-action appears to be limited mostly to a github flow branching strategy. 

E.g. if I wanted to cut release branches from develop, and merge them into master, I _could_ set my default_branch to master, but trigger release-please-action on push to develop.  The problem with this is that CHANGELOG.md or other updates added to the release-v*.*.* branch by release-please would be absent from develop, and subsequent Release PR merge conflicts would arise. 

I'm not sure how to work around this short of an option to disable automated changelog and other commits... Perhaps an option to add the changelog (or other release-type specific) commits to the _initial_ PR into develop based on the existing fix/feat commit messages when a label is included (e.g. label: `release-me`)-> generate release PR on merge to develop, with a merge target of main.

**Comment by chingor13** [comment]
The source release-please would need to implement this and we don't have plans on managing git workflows besides merging into a release branch
