### ISSUE TITLE
Ability to create draft releases

### ISSUE THREAD

**Issue by live627** [google-github-actions/release-please-action#391]
Looks like this functionality may have already been implemented in Release Please.
- https://github.com/googleapis/release-please/pull/703
- 
I tried
```yaml
        with:
          release-type: php
          draft: true
          package-name: ${{ env.MOD_NAME }}
```

but it still gets published.

I even tried modifying the action
```diff
diff --git a/action.yml b/action.yml
index 1407cb2..4e434d8 100644
--- a/action.yml
+++ b/action.yml
@@ -10,6 +10,10 @@ inputs:
     description: 'should the PR be proposed from a fork, Default to false'
     required: false
     default: false
+  draft:
+    description: 'should the release be a draft, Default to false'
+    required: false
+    default: false
   clean:
     description: 'Should stale release PRs be closed post release? Defaults to true'
     required: false
 
diff --git a/index.js b/index.js
index 0972d20..0403661 100644
--- a/index.js
+++ b/index.js
@@ -85,6 +85,7 @@ async function main () {
 
   const { token, fork, defaultBranch, apiUrl, graphqlUrl, repoUrl } = getGitHubInput()
 
+  const isDraft = getBooleanInput('draft')
   const bumpMinorPreMajor = getBooleanInput('bump-minor-pre-major')
   const bumpPatchForMinorPreMajor = getBooleanInput('bump-patch-for-minor-pre-major')
   const monorepoTags = getBooleanInput('monorepo-tags')
@@ -112,7 +113,8 @@ async function main () {
       defaultBranch,
       pullRequestTitlePattern,
       apiUrl,
-      graphqlUrl
+      graphqlUrl,
+      isDraft
     })
 
     if (releaseCreated) {
```
still no joy. And yes, I did run the build script. 

Maybe it's only a CLI option?

**Comment by live627** [comment]
https://github.com/google-github-actions/release-please-action/pull/397

**Comment by kalosisz** [comment]
Hey @live627, I haven't noticed this issue. Luckily, I independently needed this feature :100:

**Comment by kalosisz** [comment]
In you code, the variable name `isDraft` was not matching `draft`. If the name of the variable passed to the js object equals to the defined key, you don't need to specify `key: value`, compare with https://github.com/googleapis/release-please/blob/main/src/index.ts#L38 and https://github.com/google-github-actions/release-please-action/blob/3c59311372261021ff0ae2594b26ba4177d8e6c6/index.js#L105 where the label is specified explicitly.
