### ISSUE TITLE
Prerelease option

### ISSUE THREAD

**Issue by ChipWolf** [google-github-actions/release-please-action#394]
Surface the prerelease parameter from release-please

**Comment by ChipWolf** [comment]
This is now available upstream https://github.com/googleapis/release-please/pull/1200

**Comment by ChipWolf** [comment]
Workaround is to use the prerelease option in the manifest releaser.

**Comment by mrchief** [comment]
The manifest releaser doesn't seem to work correctly. E.g., I had changes in 3 packages and It created 3 releases out of which only the first one was created as prerelease. My config 
```
{
  "prerelease": true,
  "bootstrap-sha": "6f0472d2059ddbd8db6d839f2ed586a4ea790a3f",
  "packages": {
    "packages/foo": {},
    "packages/bar": {},
    "packages/johngalt": {}
  }
}
```

**Comment by mrchief** [comment]
On second look, the docs mention

> those as "Prerelease" releases that have pre-major or prerelease versions.

so it's working as advertised but also is misleading of sorts. No way to create prereleases for post major versions.

**Comment by ChipWolf** [comment]
> On second look, the docs mention
> 
> 
> 
> > those as "Prerelease" releases that have pre-major or prerelease versions.
> 
> 
> 
> so it's working as advertised but also is misleading of sorts. No way to create prereleases for post major versions.

Probably worth raising that issue upstream

**Comment by bcoe** [comment]
@ChipWolf if there's a bug with the prerelease behavior, I think we should open an issue on the release-please repository.

It sounds like along with this, we just want to add an additional configuration option to the action?
