### ISSUE TITLE
Conflict between package and module name (in `pyproject.toml`)

### ISSUE THREAD

**Issue by nok** [google-github-actions/release-please-action#396]
`release-please-action` is a useful action to improve the development lifecycle and software quality. And it's a charme that you decided to support `pyproject.toml` and [poetry](https://python-poetry.org/) (https://github.com/google-github-actions/release-please-action/issues/287). Thanks a lot! Nevertheless I found a small bug I guess.

In Python there exists different naming conventions. The official [guide of poetry](https://python-poetry.org/docs/basic-usage/) is a good and simple example to understand the issue:

First of all we create a new project.

```
poetry new poetry-demo       <--- package name
```

The generated files are:

```
poetry-demo                  <--- package name
├── pyproject.toml
├── README.rst
├── poetry_demo              <--- module name with underscore(s) (!)
│   └── __init__.py
...
```
The content of the `pyproject.toml` is:

```
[tool.poetry]
name = "poetry-demo"         <--- package name
version = "0.1.0"
...
```

After pushing to a PyPi registry:

```
pip install poetry-demo      <--- package name
```

`release-please-action` scans and parses various files automatically. The problem is that the (package) name from the `pyproject.toml` file will be used for further static checks. But that results in wrong paths, e.g.: `⚠ file poetry-demo/__init__.py did not exist`. My expection is that the _dashes_ will be replaced with _underscores_ and/or to configure the module name manually.

I tried different configurations without success. Did I miss something or is it a bug 🤔? @Mesteery

**Comment by Mesteery** [comment]
> In Python exists different naming conventions. The official guide of poetry is a good and simple example to explain and demonstrate the issue:

So if I understand, the project name and folder name must be insensitive to underscores and dashs? The project name "poetry_demo" is equal to the folder "poetry-deno", and vice versa?

This should be opened on https://github.com/googleapis/release-please. But I understand. Would you like to open a pull request? I can guide you if needed.

**Comment by nok** [comment]
Thanks for the quick response, @Mesteery . In a nutshell: It's best practice to use ...

- ... dashes in the package name, e.g. `poetry-demo`, and ...
- ... underscores in folder/module names, e.g. `poetry_demo`.

But best practices are just best practices. Technically it's not impossible to use dashes in folder names and underscores in package names. Furthermore it's possible to mix these. For example [SO](https://stackoverflow.com/q/8350853/1293700). So I answer your question with a **yes**, it must be insensitive to underscores and dashes 😄 .

By using a `pyproject.toml` file it's not required to define the folder/module name explicitly. The folder/module name will be created from the `name` implicitly (with the transformation from `-` to `_`). Nevertheless a developer **can** define the content of the package with: https://python-poetry.org/docs/pyproject/#packages .

```
[tool.poetry]
# ...
packages = [
    { include = "my_package" },
]
```

Finally I wouldn't check all possible combinations. I think that it would be enough to test whether a dash `-` is part of the package name or not. If yes, a second path will be checked, whereby the dashes are replaced by underscores:

`name` in `pyproject.toml`: `poetry-demo`

Paths to check:
- `poetry-demo/__init__.py` (current)
- `poetry_demo/__init__.py` (add)

Until now I don't have any experience with TypeScript, but I will try it out. I'm going to create a PR in the original repository the next days I guess. Thanks for your feedback!

**Comment by bcoe** [comment]
@nok thanks for the bug report, as @Mesteery mentions, it may be better to open this issue on `googleapis/release-please`, which is where this bug would need to be fixed.

**Comment by nok** [comment]
I could solve this issue by changing the value of `package-name` from `pandas-render` to `pandas_render`. It wasn't clear to me that it should be the name of the folder.

Here is my final workflow file:

```yaml
name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: python
          package-name: pandas_render
          version-path: pandas_render/__init__.py
```

Due that we can close this issue I guess. Thanks for your patience.

**Comment by trallnag** [comment]
@nok, with v3 this does not work anymore.

> Warning: Unexpected input(s) 'version-path', valid inputs are ['token', 'fork', 'clean', 'package-name', 'release-type', 'bump-minor-pre-major', 'bump-patch-for-minor-pre-major', 'path', 'changelog-path', 'command', 'version-file', 'extra-files', 'default-branch', 'changelog-types', 'config-file', 'manifest-file', 'signoff', 'github-api-url', 'github-graphql-url', 'repo-url', 'monorepo-tags', 'pull-request-title-pattern', 'draft', 'draft-pull-request']

Example: https://github.com/trallnag/testbench-release-please-python/runs/7307189577?check_suite_focus=true

It can be fixed by replacing `version-path` with `version-file`.

**Comment by trallnag** [comment]
Looking at the documentation `version-file` should not even be used by the Python strategy. I think it is best to simply make the Python strategy treat dashes and underscores the same.
