### ISSUE TITLE
Custom commit convention

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [google-github-actions/release-please-action#412]
### TL;DR

Is there a way to allow/force commit subject lines to start with an emoji/anything?

### Detailed design

I already use [commitlint](https://github.com/conventional-changelog/commitlint) which can be configured through regular expression so I assume something similar is possible with release-please. I cannot find any reference to such a customization in the release-please docs.

### Additional information

See [an example git commit history](https://github.com/edit-distance/myers-1986/commits/main) that should allow automated release/changelog creation.

**Comment by bcoe** [comment]
Hey @make-github-pseudonymous-again release-please is tied tightly to conventional commits, it uses an [AST parser](https://github.com/conventional-commits/parser) not simply a regex.

We're not likely to prioritize work to add other commit conventions -- perhaps you could use the project as a starting point though?

**Comment by bcoe** [comment]
@make-github-pseudonymous-again I could imagine adding a filter option, which allows you to remove the prefix from your commits (rather than an alternate parser).

If this would potentially solve your problem, I'd open a feature request [here](https://github.com/googleapis/release-please) 👌 .

**Comment by make-github-pseudonymous-again** [comment]
Any idea how hard it would be to allow for a custom parser module? It seems all the necessary abstraction is already there.

> I could imagine adding a filter option, which allows you to remove the prefix from your commits (rather than an alternate parser).

I feel this to be sort of a hack since it would cover exactly my use case, but why not? I'll think about it.
