### ISSUE TITLE
Feat: Support GitHub release notes generation

### ISSUE THREAD

**Issue by gusnuf** [google-github-actions/release-please-action#427]
### TL;DR

v13 of the release-please project [added support](https://github.com/googleapis/release-please/pull/1120) for the new [GitHub API](https://docs.github.com/en/rest/reference/releases#generate-release-notes-content-for-a-release) that generates release notes: .  This would be great to have access to in this action.

### Detailed design

```markdown
The new release notes generation API is exposed in the release-please library as well as the CLI, however this action does not support it.  Their docs refer to it as Changelog Type but the code also uses ChangelogNotesType, with the existing implementation being called `default` and the new type being called `github`.

Complicating matters, this action already has an input named `changelogTypes` although it might have been better named `changelogSections` as that is what it gets passed to in the library, see https://github.com/google-github-actions/release-please-action/blob/main/index.js#L132.  

There's a parity with upstream vs. backwards compatibility decision here of whether to rename the existing `changelogTypes` input.  Assuming no, the next question is whether adding `changelogType` would be too confusing or possibly to use `changelogNotesType` instead.
```

**Comment by bcoe** [comment]
this sounds like behavior we should support, would happily take contributions.

**Comment by gusnuf** [comment]
Thanks @bcoe.  I don't see any contributing guide, do you have any defined practices?  Or should I just raise a PR?

Do you have any thoughts on the backwards compatibility aspect regarding the existing input name vs. the new one?
