### ISSUE TITLE
Why is the title automatically generated in changelog not ##

### ISSUE THREAD

**Issue by kailong321200875** [google-github-actions/release-please-action#446]
### TL;DR

The title and content automatically generated in changelog are ###

### Expected behavior

The title automatically generated in changelog is ##

### Action YAML

```yaml
none
```

**Comment by bcoe** [comment]
I believe we vary the heading level depending on whether the release has features or just bug fixes. This behavior lives in [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) not in this repository.
