### ISSUE TITLE
Output for release pull request merged

### ISSUE THREAD

**Issue by ygueguin** [google-github-actions/release-please-action#475]
### TL;DR

Action be able to sent a boolean output, that give us information about pull request created status.

### Additional information

The point is to trigger specific actions only if the pull request created by the action is merged

**Comment by arifakkermans** [comment]
the **release_created** output should cover this, right?

<html>
<body>


output | description
-- | --
release_created | true if the release was created, false otherwise


</body>
</html>

**Comment by RoinujNosde** [comment]
[`release_created` ](https://github.com/google-github-actions/release-please-action#outputs)
isn't that what you need? The releases are created only after the PR is merged.
