### ISSUE TITLE
Trigger release workflow manually

### ISSUE THREAD

**Issue by kettanaito** [google-github-actions/release-please-action#524]
### TL;DR

I'd like to see a way to trigger "release-please" release manually via GitHub actions (given the `workflow_dispatch` field is enabled).

### Detailed design

```markdown
I'm not sure that the job outputs `steps[STEP_ID]outputs.releases_created` will be set properly if you trigger the release at any state of the repo as opposed to the release triggering when you merge the release pull request.

Could someone from the maintainers of this package confirm/deny this? 

Otherwise, I'd expect the action to be reproducible at any time. If there's a magical flag that's set only in certain cases, it must be changed, moving the logic of that flag to the commit and tag analyzis instead.
```

**Comment by chingor13** [comment]
> I'm not sure that the job outputs `steps[STEP_ID]outputs.releases_created` will be set properly if you trigger the release at any state of the repo as opposed to the release triggering when you merge the release pull request.

The outputs will be set if the action step creates any releases. The creation of a GitHub release tag is independent of the commit currently at HEAD -- it is looking for merged release pull requests and is tagging the SHA of the merge commit.
