### ISSUE TITLE
Tag Created by release-please-action is not triggering build

### ISSUE THREAD

**Issue by samit-manna** [google-github-actions/release-please-action#533]
Build which is supposed to triggered by "tag creation" is not running when tag is created by release-please-action. Below is the trigger used in workflow. It triggers the flow when tag is created manually but doesn't run when tag is created by release-please-action

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

**Comment by tmatsuo** [comment]
Where is the build defined?

**Comment by samit-manna** [comment]
> Where is the build defined?

Build is defined in same repo as Github Actions workflow. Below is the workflow (.github/workflows/tag.yml).

name: Tag-Build

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  Tag-Build:
    runs-on: rocc-linux
    container:
      image: docker.na1.hsdp.io/pdv-ci/philips-pdv-build-base:v1.0.1
      credentials:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
      volumes:
        - /opt/github_actions_mapping/:/opt/github_actions_mapping/
    defaults:
      run:
        shell: bash
    steps:
      - name: Build
        run: |
          echo "tag build"
