### ISSUE TITLE
`prettier --write` on `CONTRIBUTING.md` and `.release-please-manifest.json` in PRs

### ISSUE THREAD

**Issue by quinn-dougherty** [google-github-actions/release-please-action#542]
### TL;DR

I would like for the generated `CONTRIBUTING.md` and `.release-please-manifest.json` formatting to be `prettier`-compliant. 

### Detailed design

```markdown
Could be a wrapper around the core logic that's already in the action
```

**Comment by tobiasdiez** [comment]
Also applies to the changelog that is created in the release PR.

@quinn-dougherty did you have a workaround?

**Comment by chingor13** [comment]
This would need to be implemented on the upstream googleapis/release-please library
