### ISSUE TITLE
QUESTION: Proper way to configure a node project in subdirectory

### ISSUE THREAD

**Issue by billchurch** [google-github-actions/release-please-action#543]
This is working pretty great in my testing so far, however I think i'm missing the connection to get this to work exactly as I would like it (meaning, I think it can work the way I want it to but I think I'm doing it wrong). This probably has more to do with how I have my node project setup, and less about release-please-action.

I have a repo [webssh2](https://github.com/billchurch/webssh2)
- It contains a single nodejs package/project which lives in [/app](https://github.com/billchurch/webssh2/tree/main/app)
- I'd like to have release-please take over changelog and release generation (it technically works)
- Would like everything to run via github actions (it sort of works)
- would like the tags create to be just the version number (no `v` prefix, no application name prefix
- would like to publish to npm when released (for some reason I don't seem to be ever returning `steps.release.outputs.releases_created` but I've been experimenting with pre-releases so maybe that's it?

Ideally i'd just maintain this from github actions, but I need to bootstrap it first, so I went with the manifest method.

Manifest files located at:
- [.release-please-manifest.json](https://github.com/billchurch/webssh2/blob/main/.release-please-manifest.json)
- [release-please-config.json](https://github.com/billchurch/webssh2/blob/main/release-please-config.json)

My current github workflow/action is: [release.yml](https://github.com/billchurch/webssh2/blob/main/.github/workflows/release.yml).

I don't see a way through the manifest or through github actions to enable to the `include-v-in-tags` cli option. I tried just adding it to the release-please-config as well as a github action but I see no option. 

Finally I've hit my API rate due to my testing so I'm going to give it a break for a bit. 

Appreciate any input here, this is a great looking project and hope to get my installation cleaned up so I can use it.

**Comment by fynnfeldpausch** [comment]
I have the same problems setting up a single _npm_ project that is released from a subfolder. For Angular projects, this is pretty much standard behaviour, as library projects are located in a `projects` folder.

**Comment by bcoe** [comment]
Here's a mono-repo that has been setup as described:

https://github.com/istanbuljs/istanbuljs/blob/master/.github/workflows/release-please.yml

I use a `paths_released` output, which it looks like we've failed to document.

**Comment by bcoe** [comment]
@billchurch @fynnfeldpausch does this work for your use-case, if so I can document in the README.
