### ISSUE TITLE
Allow GitHub Enterprise not to specify changelog-host

### ISSUE THREAD

**Issue by goatwu1993** [google-github-actions/release-please-action#588]
### TL;DR

Now workflows in GitHub Enterprise needs to specify changelog-host to the GitHub Enterprise URL, which can be easily avoided.

### Detailed design

Replace the default value of `changelog-host` from 'https://github.com' to `${{ github.server_url}}`

**Comment by goatwu1993** [comment]
oops. This issues seems to be deplicated with #508

**Comment by chingor13** [comment]
Fixed in #587
