### ISSUE TITLE
Does it support "Two package.json Structure" of electron-builder?

### ISSUE THREAD

**Issue by zxcvbnm3057** [google-github-actions/release-please-action#600]
It seems that `Release-Please` only read metedata from single package.json. But with "[Two package.json Structure](https://www.electron.build/tutorials/two-package-structure.html)" of electron-builder, all of the meta fields should be in the app/package.json (version, name and so on) . So is there any plugin or anything could read these information from the inner folder?

**Comment by tmatsuo** [comment]
Does `path` configuration work for you?

**Comment by tmatsuo** [comment]
Please open if it doesn't work for you :)

**Comment by zxcvbnm3057** [comment]
> Does `path` configuration work for you?

No, it doesn't. Release Please will only consider commits that touch files on that path after `path` is set. But I need to publish whole project but change version number in the file `./release/app/package.json`, not the default package.json at the root of repository. I am tring with `extra-files` but don't know if this is working.
