### ISSUE TITLE
Provide current data/timestamp of release 

### ISSUE THREAD

**Issue by aaronware** [google-github-actions/release-please-action#602]
### TL;DR

When releasing a version we find it useful to provide the date of release within our readme files. It would be great to provide the date for use within files (being updated) in addition to also doing the other version bumps if possible

### Additional information

Example: Our readme.md has

## Latest Release [1.2.3] 09-02-2022

it would be great to bump that date to the date of the latest merge instead of doing another action

**Comment by chingor13** [comment]
Please re-open this feature request on the upstream library: https://github.com/googleapis/release-please
