### ISSUE TITLE
Push to main automatically

### ISSUE THREAD

**Issue by riccardosalamanna** [google-github-actions/release-please-action#603]
### TL;DR

Would it be possible to have the functionality of release-please without the PR? As in, push directly to main branch without need for approval? thanks

**Comment by chingor13** [comment]
This is outside the design of release-please -- we do not and do not plan to support directly pushing to main.

We suggest finding/building an automerge automation if you want this feature.

**Comment by riccardosalamanna** [comment]
ok thanks i appreciate the answer! 👍
