### ISSUE TITLE
Edit Conventional Commits

### ISSUE THREAD

**Issue by bartutiryakioglu** [google-github-actions/release-please-action#630]
### TL;DR

We need more conventions for our development team. We need a way to modify the conventional commits.

### Detailed design

I couldn't find a description for how to change the way code reads the commits. For Example, I want to add improvement and package change titles for the change log file. Is there a way to do it with the current version?

**Comment by bartutiryakioglu** [comment]
Also, can I use commit descriptions and commit titles for changelog?

**Comment by chingor13** [comment]
This action wraps the underlying [release-please library](https://github.com/googleapis/release-please). There is an option for updating the changelog sections.

I would suggest that you switch to a ["manifest"](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md) configuration for any complex customizations (not all customization options will be propagated to action inputs in the future). Additionally, the manifest config files have a [published JSONSchema](https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json) which can be used for validation and documentation of every available option.

If you're looking to rewrite a commit message and you are using pull requests, there's also a feature for that: https://github.com/googleapis/release-please#how-can-i-fix-release-notes
