### ISSUE TITLE
Question: Is there a convenient way to auto merge release PRs?

### ISSUE THREAD

**Issue by barkin94** [google-github-actions/release-please-action#649]
I've been trying to figure out how to properly auto-merge release PRs in order to fully automatize deployments. I could possibly make it work via other actions, but I'm not sure if I should. I don't want to risk polluting workflow config files with unnecessary jobs and steps, so I was wondering if there is a recommended way to achieve this. Or should I handle this situation in an entirely different way? If I'm looking at this the wrong way, please feel free to correct me, as I am trying to learn myself.

**Comment by chingor13** [comment]
We don't really provide prescriptive guidance on how you should automate auto-merging of pull requests. We generally require a human to approve releases in our workflows.

In general, any kind of CI/CD system could be leveraged to respond to pull request events and approve/merge a pull request.

**Comment by airtonix** [comment]
If you want to auto merge an autogenerated release PR, then you don't want release-please.

You just need something like [semantic-release](https://github.com/semantic-release/semantic-release) which will generally do all the same things without a collated release pr: consider versions based on commit messages, update changelogs.
