### ISSUE TITLE
How can I set custom multiple labels?

### ISSUE THREAD

**Issue by ar-bella-jeong** [google-github-actions/release-please-action#668]
### TL;DR

when setting labels field, how to set multiple labels?
There is `labels` is list field in docs.

### Action YAML

```yaml
...
  labels: 'wip'
...
```

**Comment by chingor13** [comment]
The labels field use [core.getMultilineInput()](https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L148-L161) - separate your entries by newlines.
