### ISSUE TITLE
Add support for defining `changelog-types` as YAML

### ISSUE THREAD

**Issue by NateEag** [google-github-actions/release-please-action#708]
### TL;DR

It's hard to read a lengthy `changelog-types` entry.

It would be easier if we could represent them as normal YAML within the file.

### Detailed design

Backwards compatibility should be easy to maintain - if the `changelog-types` field is a string,  parse it as JSON. Otherwise, treat it as YAML.

### Additional information

Would a PR implementing this be accepted?

**Comment by chingor13** [comment]
For complicated options, use [a manifest config](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#configfile) (even for a single component repository). The full schema can be found [here](https://github.com/googleapis/release-please/blob/main/schemas/config.json). We can't maintain every config option added to release-please as a github action input.
