### ISSUE TITLE
Incorrect number of commits found between SHA and HEAD 

### ISSUE THREAD

**Issue by lance** [google-github-actions/release-please-action#78]
In one of my projects that is [using this action](https://github.com/cloudevents/sdk-javascript/pull/341), I am seeing some strange behavior. Here is output from the most recent run.

```console
Run GoogleCloudPlatform/release-please-action@v2.4.1
✖ no recent release PRs found
✔ found 585 commits since b9ed2619c0362390c221e9bf8bf61deea7bd83fd
✔ release as major: There are 9 BREAKING CHANGES and 12 features
✔ updating package-lock.json from 3.1.0 to 4.0.0
✖ file samples/package.json did not exist
✔ updating CHANGELOG.md
✔ updating package.json from 3.1.0 to 4.0.0
✔ update pull-request #341: chore: release 4.0.0
✔ adding label autorelease: pending to https://github.com/cloudevents/sdk-javascript/pull/341
✔ cloudevents/sdk-javascript find stale PRs with label "autorelease: pending"
```

It found 585 commits between `b9ed26` and `HEAD`. But if I make a fresh clone of the repository, I see something quite different using `git log` - 20 commits. 

```console
❯ git clone git@github.com:cloudevents/sdk-javascript.git                                                              617ms  Thu 01 Oct 2020 03:35:57 PM EDT
Cloning into 'sdk-javascript'...
remote: Enumerating objects: 78, done.
remote: Counting objects: 100% (78/78), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 4197 (delta 27), reused 40 (delta 20), pack-reused 4119
Receiving objects: 100% (4197/4197), 1.96 MiB | 5.50 MiB/s, done.
Resolving deltas: 100% (2344/2344), done.

~/tmp 
❯ cd sdk-javascript/                                                                                                  1211ms  Thu 01 Oct 2020 03:35:59 PM EDT

sdk-javascript on  main is 📦 v3.1.0 
❯ git log b9ed2619c0362390c221e9bf8bf61deea7bd83fd..HEAD --oneline                                                             Thu 01 Oct 2020 03:36:01 PM EDT
138de37 (HEAD -> main, origin/main, origin/HEAD) docs: update README with latest API changes (#347)
76688c4 chore: update release please to the latest release(2.4.1) (#345)
e334b6e feat: add emitterFactory and friends (#342)
a9114b7 chore: add an automated GH action for releases (#329)
eca43d9 fix: package.json & package-lock.json to reduce vulnerabilities (#338)
0a12146 docs: update README with maintainer names (#337)
1fa3a05 feat: add a constructor parameter for loose validation (#328)
7423acb fix: upgrade cloudevents from 3.0.1 to 3.1.0 (#335)
4779d89 chore(example): Replaced body parser with express JSON parser (#334)
6cd310c src(event)!: make the event's time property only a string (#330)
f3953a9 feat: introduce Message, Serializer, Deserializer and Binding interfaces (#324)
17d4bc8 chore: add cucumber.js to list of files to lint and /docs to .gitignore (#327)
73f0bec chore: Update README with correct links for the support specification versions (#321)
0adcc35 chore: Remove commented version import. (#319)
6e2390e fix: upgrade uuid from 8.2.0 to 8.3.0 (#317)
4bf2eb8 chore: Update references of master to main (#316)
b5cf886 test: implement pending tests leftover from TS rewrite (#315)
8ac3eb0 refactor: validate cloudevent version agnostic (#311)
81623ac chore: typo (#313)
b3624c2 docs: add ref to CoC and other things (#244)
```

**Additional Context**
The SHA that it's using is from the most recent tag, which is on a separate branch. I'm not sure if that would cause this kind of problem, but it's unclear to me why that would make a difference based on a quick glance at [the `release-please` code](https://github.com/googleapis/release-please/blob/master/src/graphql-to-commits.ts#L74-L102).

**Comment by bcoe** [comment]
@lance releasae-please currently has the limitation that it expects the latest tag will point to the primary branch.

There's some work that is close to being finished that allows for other branches, it might solve the issue:

https://github.com/googleapis/release-please/pull/429

**Comment by lance** [comment]
@bcoe thanks for the update. I will keep an eye on it.

**Comment by bcoe** [comment]
@lance `v2.5.5` has the updated logic, try it and let me know if it solves your problem for you?

**Comment by lance** [comment]
@bcoe thanks for following up on this. I have bumped to `v2.5.5` but that did not seem to solve it. See https://github.com/cloudevents/sdk-javascript/pull/351

```
Run GoogleCloudPlatform/release-please-action@v2.5.5
✖ no recent release PRs found
[
  { type: 'feat', section: 'Features', hidden: false },
  { type: 'fix', section: 'Bug Fixes', hidden: false },
  { type: 'docs', section: 'Documentation', hidden: false },
  { type: 'chore', section: 'Miscellaneous', hidden: false },
  { type: 'src', section: 'Miscellaneous', hidden: false },
  { type: 'style', section: 'Miscellaneous', hidden: false },
  { type: 'refactor', section: 'Miscellaneous', hidden: false },
  { type: 'perf', section: 'Performance', hidden: false },
  { type: 'test', section: 'Tests', hidden: false }
]
✔ found 582 commits since beginning of time
✔ updating package-lock.json from 3.1.0 to 1.0.0
✖ file samples/package.json did not exist
✔ updating CHANGELOG.md
✔ updating package.json from 3.1.0 to 1.0.0
✔ adding label autorelease: pending to https://github.com/cloudevents/sdk-javascript/pull/351
✔ cloudevents/sdk-javascript find stale PRs with label "autorelease: pending"
✖ closing pull #348 on cloudevents/sdk-javascript
```

**Comment by jef** [comment]
> It closed the PR for v4.0.0 and opened a new one for v1.0.0.

Same here on mine.

**Comment by bcoe** [comment]
@jef could you provide an example repository that you are bumping into this issue on?

**Comment by bcoe** [comment]
@lance I didn't realize you'd never used release-please release on that repository before, the problem is that it has no way to determine the `sha` of your last release:

1. the new logic we've been working on looks for a prior merged PR, of the form `release-vx.y.z` (_this won't work, because there's never been a PR merged with this branch structure_).
2. prior to this it looked for your latest SemVer tag, and used this as a starting point (_this won't work because your tag points to `v3.x.x` which does not share a history with your default branch_).

## Solution 1

You could create a PR with the expected branch structure:

```
git checkout -b release-v2.0.4
git commit --allow-empty -m "chore: tag HEAD as 2.0.4 release
```

At this point, your `v3.x.x` tags shouldn't cause any issues, and you'll be able to continue releasing from the `v2.x.x` release line.

----

@jef could you open a separate issue, I'm guessing your likely bumping into  completely different issue/

**Comment by jef** [comment]
> @jef could you provide an example repository that you are bumping into this issue on?

Sure no problem. I tried to do some work around (I thought I broke it somehow 😅), you'll see in recent commits to main.

github.com/jef/nvidia-snatcher

**Comment by jef** [comment]
Looks good after the hotfix. Thanks @bcoe!

**Comment by lance** [comment]
@bcoe thanks for the follow up. I will give this a try today.

**Comment by bcoe** [comment]
@jef my concern with the hot fix is it shouldn't be necessary in cases other than lance's, i.e., if we're able to find the last release ... I don't love that we'd now be maintaining both approaches for finding an old release (_looking up by tags, and by branch name).

**Comment by bcoe** [comment]
@lance @jef closing this, as I believe it's addressed for both of you? let me know if this issue crops up again?

**Comment by jef** [comment]
Sounds good to me. Thanks!

**Comment by lance** [comment]
Thanks for helping out @bcoe
