### ISSUE TITLE
Be able to configure the changelog template or at least include the username of the contributors to the feature

### ISSUE THREAD

**Issue by RicardoE105** [google-github-actions/release-please-action#784]
### TL;DR

It would be awesome to reference the user that created the PR in the release PR body. See the example (red) below:
<img width="834" alt="Screenshot 2023-06-24 at 9 06 14 PM" src="https://github.com/google-github-actions/release-please-action/assets/16496553/47daed41-07b3-461f-b993-9edd3b164361">

**Comment by chingor13** [comment]
Thanks for this, but this will need to be added in the upstream https://github.com/googleapis/release-please library
