### ISSUE TITLE
Ability to specify multiple release-types

### ISSUE THREAD

**Issue by amaanq** [google-github-actions/release-please-action#792]
### TL;DR

For a project of mine, I have node and rust bindings, and I want both to be updated with release-please, but it seems like only one can be at a time. A way to specify an array of `release-types` would be nice, then I could just set that to ["node", "rust"].

**Comment by chingor13** [comment]
Please use the `manifest` command option and check out the configuration options from the upstream library: https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md

**Comment by amaanq** [comment]
I did see that - but the issue is my rust crate and npm package are both in ".", I don't think I can have duplicate key entries in json, right?
