### ISSUE TITLE
How to use it to release a github action?

### ISSUE THREAD

**Issue by yiliang114** [google-github-actions/release-please-action#807]
### TL;DR

Recommended to add `github-action` as `release-type`'s option.

### Detailed design

Use [release-please-action](https://github.com/google-github-actions/release-please-action) to release a github action, Although the version will be released automatically, the version on the application market will not be updated automatically.

**Comment by chingor13** [comment]
`release-please` only bumps code, creates tags/GitHub releases. It does not actually publish anything else besides that.

The `release-type` configuration is for assisting in bumping versions in well-known places in code. For a GitHub action, this is probably not necessary so a `simple` `release-type` should work.
