### ISSUE TITLE
Aggregate 2 or more pre-release changelog become 1 changelog when release

### ISSUE THREAD

**Issue by vhermawan** [google-github-actions/release-please-action#809]
### TL;DR

When I create tag v1.1.0-rc1 (pre-release) it has 1 changelog. Then, I create a new tag v1.1.0-rc2 (pre-release) it has 1 changelog. After that i create release version v1.1.0 it should have 2 changelogs (aggregate from v1.1.0-rc1 and v1.1.0-rc2). 

But for now, it is just 1 changelog created from GitHub actions, because it just read from a last commit to create a changelog.

**Comment by philippeboyd** [comment]
Not quite sure if linked but we just had a similar issue where we created 1 PR containing 2 commits. For context we have a monorepo with the following (redacted) folder (release please components)

* dbt-customer-abc
* dbt-source-x

1. 1st commit handles an edit (non breaking change `feat: ...`) in `dbt-source-x`
2. 2nd commit handles edits (breaking change `feat!: ...`) in `dbt-customer-abc` which depends on `dbt-source-x`

When we merged the PR, we had the changelog of `dbt-source-x` containing the commit message of the 2nd commit which should not appear in that `dbt-source-x` changelog but only in `dbt-customer-abc`'s changelog.

The github action correctly created a second PR for the breaking change of `dbt-customer-abc` but that breaking change should not be listed in `dbt-source-x`

**Comment by chingor13** [comment]
This would be a feature request to the underlying release-please library (https://github.com/googleapis/release-please). These versioning schemes are very custom and not everyone wants it the same way.

That feature needs a robust design and cannot be tracked here. Feel free to start a new discussion/design idea on the upstream release-please library.
