### ISSUE TITLE
Co-authored statement seemingly breaks workflow

### ISSUE THREAD

**Issue by VividLemon** [google-github-actions/release-please-action#846]
### TL;DR

This could be an upstream issue to the release-please parser, but adding a co-authored statement seemingly stops reading the commit

Taking the following commit
https://github.com/bootstrap-vue-next/bootstrap-vue-next/commit/06e875eca6a3a055c65246619ee11ab19ef59be4

The breaking commits in the commit body should be parsed. But it didn't

### Expected behavior

The breaking commits in the commit body should be parsed. But it didn't

### Observed behavior

The commit isn't added to the release

### Action YAML

```yaml
https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/.github/workflows/release-main.yaml
```

### Log output

```text
https://github.com/bootstrap-vue-next/bootstrap-vue-next/actions/runs/6670295661/job/18129851942
```

**Comment by chingor13** [comment]
The `---------` is breaking the conventional commit parsing as it's not part of the spec. The commit parser reads git footers (`<something>: <something>`) from the bottom of the commit messages. If it finds lines that don't match that pattern, then it assumes the rest above is an extended description.

Care should be taken when merging PRs to make sure the actual commit message follows the spec. You can fix the release notes with https://github.com/googleapis/release-please#how-can-i-fix-release-notes

**Comment by VividLemon** [comment]
> The `---------` is breaking the conventional commit parsing as it's not part of the spec. The commit parser reads git footers (`<something>: <something>`) from the bottom of the commit messages. If it finds lines that don't match that pattern, then it assumes the rest above is an extended description.
> 
> Care should be taken when merging PRs to make sure the actual commit message follows the spec. You can fix the release notes with https://github.com/googleapis/release-please#how-can-i-fix-release-notes

To me it seems strange that it wouldn't parse through each item individually, perhaps line by line. Because as shown, there is useful metadata contained within a commit message, but isn't added to the release
