### ISSUE TITLE
Allow creating a GitHub Discussion for a GitHub Release

### ISSUE THREAD

**Issue by holtgrewe** [google-github-actions/release-please-action#853]
### TL;DR

The `gh` CLI allows to easily create a discussion when creating a release. That would be nice to have in `release-please-action` as well.

### Detailed design

Add a setting `gh-discussion-category` that triggers the same behaviour as `gh release create --discussion-category $CAT`.

### Additional information

See here for the documentation for `--discussion-category`:

- https://cli.github.com/manual/gh_release_create

**Comment by chingor13** [comment]
Thanks for this, but this is outside the scope of what we want release-please to do (it's not a common thing that most releases use). Because this is available as a GitHub action and it provides outputs, developers can chain together events to do this with external tools.
