### ISSUE TITLE
Drop advanced configuration options

### ISSUE THREAD

**Issue by chingor13** [google-github-actions/release-please-action#858]
### TL;DR

There are so many configuration options in release-please. It is infeasible to continue to pipe every option as an input. There are a few rare options that should be kept to make a quick start possible (`release-type`, `path`, `fork`).

### Detailed design

Any advanced configuration options should use a release-please manifest config. This will allow users to also use the release-please CLI to debug their configuration which is not possible when configuring your repository using action inputs.

**Comment by steveoh** [comment]
this is making our release cycle so much more difficult or even impossible :/
