### ISSUE TITLE
Github Fine-grained Personal Access Tokens

### ISSUE THREAD

**Issue by tippmar-nr** [google-github-actions/release-please-action#872]
Our organization has recently prohibited the use of "classic" personal access tokens and we've so far been unable to figure out the right set of permissions for the new "Fined-grained" personal access tokens that will allow Release Please to run successfully.  

Here's our latest attempt:
![image](https://github.com/google-github-actions/release-please-action/assets/120425148/b5b96ce8-9051-4001-8368-eca6ff31bf2a)

Which fails with 
```
 Found pull request #2064: 'chore(main): release 10.20.0'
✔ Building release for path: .
❯ type: go
❯ targetBranch: main
✔ Creating 1 releases for pull #2064
Error: release-please failed: Resource not accessible by personal access token
```

If anyone is using a fine-grained token, could you please share the set of permissions your token has?

**Comment by tippmar-nr** [comment]
We apparently were able to stumble into the right set of permissions and now the Release Please action is working. I'm sure this token has way more permission than it needs, but it's working now so I'm not going to mess with it... 

If anyone does have specific guidance they can offer, it would be appreciated.


![image](https://github.com/google-github-actions/release-please-action/assets/120425148/09f9ef96-8307-4401-bd3e-f359d58cb580)

**Comment by DanielHabenicht** [comment]
For anyone for whom the image is not visible anymore: 

> You need:
> 
> A fine-grained PAT
> The resource owner needs to match the repo owner/org
> It needs write access to:
>  - contents
>  - pull requests
>  - workflows
>  
> The thing I was missing was write access to workflows. This is the magic that lets you POST to repos/{org}/{repo}/releases.

Brought to you by: https://github.com/googleapis/release-please-action/issues/878#issuecomment-1833398511
