### ISSUE TITLE
Adding "alpha" when prelease is set to True

### ISSUE THREAD

**Issue by dinjazelena** [google-github-actions/release-please-action#877]
### TL;DR

Hey, so most of the time versioning for development environment we do set as pre-release on Github Releases, but how can i use this to append "alpha.1" or "alpha.2" when i want to publish somewhere this? How can i include alpha in tag?

**Comment by chingor13** [comment]
This (https://github.com/googleapis/release-please/pull/2083) might be what you're looking for, but is included in v16.1.0 of release-please which will be in v4 of the action (not yet released).
